### ISSUE TITLE
Hilt Singleton annotations in repository

### ISSUE THREAD

**Issue by roby222** [PatilShreyas/ViewModelGoodPractice#3]
Hi,  
I'm wondering why you repeated the Hilt Singleton annotations in the UserRepository Class?

They are already explicit declared in DI module?

```
@Module
@InstallIn(SingletonComponent::class)
interface RepositoryModule {
	@Singleton
	@Binds
	fun userRepository(repository: InMemoryUserRepository): UserRepository
```

So you don't need to add hilt references in the UserRepository

```
@Singleton //not necessary?
interface UserRepository {
	suspend fun findById(id: Int): User
	suspend fun add(name: String, email: String): User
}

@Singleton  //not necessary?
class InMemoryUserRepository @Inject constructor() : UserRepository { 
```

What do you think?

thanks
Roberto

**Comment by PatilShreyas** [comment]
Yeah, you're correct, it's not necessary since it is present in the Module. 

_Closing this since it's not an issue_
